version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "chloe-the-catgirl"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - chloe-the-catgirl
    open-pull-requests-limit: 5
