version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - nachtjasmin

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - nachtjasmin
    groups:
      all:
        patterns: ["*"]
        update-types: [ minor, patch ]
